---
services:
  sinusbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: git.techniverse.net/scriptos/sinusbot:1.0.2
    container_name: sinusbot
    hostname: sinusbot
    networks:
      sinusbot_net:
        ipv4_address: 172.29.84.10
    user: "1000:1000"
    ports:
      - "8087:8087"
    volumes:
      - ./data/config.ini:/opt/sinusbot/config.ini
      - ./data/data:/opt/sinusbot/data
      - ./data/scripts:/opt/sinusbot/scripts
    restart: unless-stopped

networks:
  sinusbot_net:
    name: sinusbot.dockernetwork.local
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.84.0/24
          gateway: 172.29.84.1
          ip_range: 172.29.84.128/25
